apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: jmco1w9qp-python 
  janus-idp.io/tekton: jmco1w9qp-python
  backstage.io/kubernetes-id: jmco1w9qp-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: jmco1w9qp-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml